# Generated by Django 3.0.3 on 2020-04-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Blood_Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Rh_factor',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='Blood_Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='Rh_factor',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
