# Generated by Django 3.0.3 on 2020-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200417_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(default=' ', help_text='eg : #112 Sector 40C, Chandiarh', max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='address',
            field=models.CharField(default=' ', help_text='eg : #112 Sector 40C, Chandiarh', max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='blood_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seeker',
            name='hospital_address',
            field=models.CharField(default=' ', help_text='eg: sector 16, Chandiagrh', max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='hospital_name',
            field=models.CharField(default=' ', help_text='eg: GMSH', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Blood_Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Rh_factor',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], help_text=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text=' ', max_length=6),
        ),
    ]
