# Generated by Django 3.0.3 on 2020-04-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200419_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='Blood_Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='Rh_factor',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], help_text=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text=' ', max_length=6),
        ),
    ]
