# Generated by Django 3.0.3 on 2020-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200419_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='show',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Can we make your contact details public for people in need to contact you?'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(default=' ', help_text='eg : #112 Sector 40C, Chandigarh', max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='hospital_address',
            field=models.CharField(default=' ', help_text='eg: sector 16, Chandigarh', max_length=100),
        ),
    ]
