# Generated by Django 3.0.3 on 2020-06-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200509_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='blood_type',
            field=models.CharField(choices=[('PRBC', 'PRBC'), ('WB', 'WB'), ('FFP', 'FFP'), ('PC', 'PC'), ('CRYO', 'CRYO')], default=' ', max_length=4),
        ),
    ]
