# Generated by Django 3.0.3 on 2020-05-29 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20200509_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Group', models.CharField(max_length=2)),
                ('Rh_factor', models.CharField(max_length=1)),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.donor')),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='WB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'expired'), (True, 'active')], default=True)),
                ('blood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.Blood')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Payment_option', models.CharField(max_length=20)),
                ('Status', models.BooleanField(default=False)),
                ('Seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='PRBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'expired'), (True, 'active')], default=True)),
                ('blood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.Blood')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'expired'), (True, 'active')], default=True)),
                ('blood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.Blood')),
            ],
        ),
        migrations.CreateModel(
            name='FFP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'expired'), (True, 'active')], default=True)),
                ('blood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.Blood')),
            ],
        ),
        migrations.CreateModel(
            name='CRYO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'expired'), (True, 'active')], default=True)),
                ('blood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.Blood')),
            ],
        ),
    ]
